# Generated by Django 5.1 on 2024-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='chatfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
